#!/bin/dash
HOSTS_FILE=~/.ssh/known_hosts

echo "Checking hosts in ${HOSTS_FILE} to see if they are live."

IP_ADDRS=$(cut -d' ' -f1 ${HOSTS_FILE} | grep -oh '[0-9][0-9]\?[0-9]\?\.[0-9][0-9]\?[0-9]\?\.[0-9][0-9]\?[0-9]\?\.[0-9][0-9]\?[0-9]\?')
for IP in ${IP_ADDRS}
do
    ping -c5 -n -i 0.5 ${IP} > /dev/null
    ERR=$?
    if [ ${ERR} -ne 0 ]; then
        echo ${IP}: no response
    else
        echo ${IP}: OK
    fi
done
DSN_NAMES=$(grep -v '[0-9][0-9]\?[0-9]\?\.[0-9][0-9]\?[0-9]\?\.[0-9]' ${HOSTS_FILE} | cut -d' ' -f1)
for NAME in ${DSN_NAMES}
do
    ping -c5 -n -i 0.5 ${NAME} > /dev/null 2>&1
    ERR=$?
    if [ ${ERR} -ne 0 ]; then
        echo ${NAME}: no response
    else
        echo ${NAME}: OK
    fi
done
