#!/usr/bin/env python

import sys

if len(sys.argv) > 1:
    file_name = sys.argv[1]
    fd = open(file_name, 'r')
else:
    fd = sys.stdin

prev_line = ""

for line in fd:
    if prev_line != line:
        print line,
        prev_line = line
