#!/usr/bin/env dash
# TODO: accept NITF version as parameter, and/or prompt for it

DTD_DOC="/home/aflanagan/xsd/nitf-3-3.dtd"
#DTD_DOC="http://www.nitf.org/site/nitf-documentation/nitf-3-1.dtd"

if [ $# -lt 1 ]; then
    echo "Usage: $(basename $0) nitf_xml_file [...]"
    echo "       Validates an XML file against the NITF 3.3 DTD."
    echo "       Prints errors found, or nothing if files are OK."
else
    #xmllint "$1" --noout --dtdvalid http://www.iptc.org/std/NITF/3.4/specification/dtd/nitf-3-4.dtd
    for FNAME in "$@"
    do
        xmllint "${FNAME}" --noout --dtdvalid ${DTD_DOC}
    done
fi
