#!/bin/sh
# -*- mode: shell-script; coding: utf-8; -*-
#
# tangle files with org-mode
#
DIR=`pwd`
FILES=""

# wrap each argument in quotes, required to call tangle on it
for i in $@; do
FILES="$FILES \"$i\""
done

CALL_TANGLE="(progn
(require 'org)
(mapc (lambda (file)
   (find-file (expand-file-name file \"$DIR\"))
(org-babel-tangle)
(kill-buffer)) '($FILES)))"

emacs -Q --batch --eval "${CALL_TANGLE}"
