#!/usr/bin/env dash

USERNAME=lloyd
CERTFILE=${HOME}/.ssh/id_rsa.personal
HOSTNAME=SLICE-152624
# HOSTNAME=107.189.11.203

echo "ssh -i ${CERTFILE} ${USERNAME}@${HOSTNAME}"
echo "----------------------------------------------------------------------------------------------"
ssh -i ${CERTFILE} ${USERNAME}@${HOSTNAME}
